# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
#rdiscount:
#  extensions: [smart]
permalink: /:title
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://hautahi.com/
description: Kia ora, I'm an economist based in Washington DC.
baseurl: / 
title: Hautahi Kingi
author: Hautahi Kingi
description: Personal website
avatar: profile.jpg
#email: yourname@email.com
#github: biomadeira/sustain # username
#twitter: username
#linkedin: username
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: hautahi
google_analytics: UA-90951306-1


# needed for travis-ci build
exclude: [vendor]
